# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-15 05:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=256, verbose_name='name')),
                ('passwd', models.CharField(max_length=256, verbose_name='passwd')),
            ],
        ),
        migrations.DeleteModel(
            name='Article',
        ),
    ]
